name: 'jstest'
description: 'figuring out how to call git meta data from gh actions'
inputs:
  github-token:  # id of input
    description: 'the GH token to connect to github from the action'
    required: true
  dry-run: 
    description: "check if the action would succeed"
    required: false
    default: "FALSE"
  bump: 
    description: "which part of the semver needs to be updated?"
    required: true
    default: "minor"
  branch: 
    description: "force to tag a specific branch"
    required: false
    default: ""
outputs:
  new-tag: # id of output
    description: 'new tag'
  tag: # id of output
    description: 'latest tag'
runs:
  using: 'node12'
  main: 'dist/index.js'