# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - id: contributor 
      run: echo ::set-output name=release::minor
      if: github.actor == 'phish108'

    - id: bot
      run: echo ::set-output name=release::patch
      if: startsWith(github.actor, 'dependabot')

    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    
    - id: tagger
      uses: phish108/autotag-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        bump: ${{ steps.contributor.outputs.release || steps.bot.outputs.release }}
        dry-run: 'TRUE'
        
    - run: | 
        npm run package
        npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new-tag }} 
        git commit -m "updated dist file for $GITSHA" -a 
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: phish108/autotag-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        bump: ${{ steps.contributor.outputs.release || steps.bot.outputs.release }}
