# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master Integration

on:
  push:
    branches: 
    - master 
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run lint

  test:
    needs: lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    
    - id: tagger
      uses: phish108/autotag-action@1.1.26
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: 'TRUE'
    
    - name: Autotag Draft
      uses: phish108/autotag-action@master
      id: taggerTest
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        dry-run: 'true'

    - name: verify Tags
      run: |
        if [ "${{ steps.tagger.outputs.new-tag }}" != "${{ steps.taggerTest.outputs.new-tag }}" ]
        then
          exit 1
        fi

  verify: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: check changes
        id: release
        uses: phish108/release-check@1.0.3
      - name: only dev changes
        run: exit 1
        if: ${{ steps.release.outputs.hold_development }}
      - name: only protected changes
        run: exit 1
        if: ${{ steps.release.outputs.hold_protected }}
      - name: Proceed to release
        run: echo OK

  build:
    needs: verify

    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    
    - id: tagger
      uses: phish108/autotag-action@1.1.26
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: 'TRUE'
    
    - run: | 
        npm ci
        npm run package
        npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new-tag }} 
        sed -ire "s/phish108\/autotag-action@[0-9]*\.[0-9]*\.[0-9]*/phish108\/autotag-action@${{ steps.tagger.outputs.new-tag }}/g" README.md
        git commit -m "updated dist file for $GITSHA" -a 
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: phish108/autotag-action@1.1.26
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
