# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 14.x

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }} 
    
    - id: tagger
      uses: phish108/autotag-action@1.1.26
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: 'TRUE'
    
    - name: Autotag Draft
        uses: phish108/autotag-action@master
        id: taggerTest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          dry-run: 'true'

      - name: verify Tags
        run: |
          if [ "${{ steps.tagger.outputs.new-tag }}" != "${{ steps.taggerTest.outputs.new-tag }}" ]
          then
            exit 1
          fi

    - run: | 
        npm ci
        npm run package
        npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new-tag }} 
        sed -ire "s/phish108\/autotag-action@[0-9]*\.[0-9]*\.[0-9]*/phish108\/autotag-action@${{ steps.tagger.outputs.new-tag }}/g" README.md
        git commit -m "updated dist file for $GITSHA" -a 
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: phish108/autotag-action@1.1.26
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
